# Generated by Django 6.0.1 on 2026-01-16 12:17

import apps.catalog.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Создание'), ('update', 'Обновление'), ('delete', 'Удаление'), ('status_change', 'Изменение статуса')], max_length=20, verbose_name='Действие')),
                ('changes', models.JSONField(default=dict, help_text='Детали изменений в формате JSON', verbose_name='Изменения')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время изменения')),
            ],
            options={
                'verbose_name': 'История изменений',
                'verbose_name_plural': 'История изменений',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Максимальный размер файла: 10MB', upload_to=apps.catalog.models.get_image_upload_path, validators=[apps.catalog.models.validate_image_size], verbose_name='Оригинальное изображение')),
                ('thumbnail', models.ImageField(blank=True, editable=False, null=True, upload_to=apps.catalog.models.get_thumbnail_upload_path, verbose_name='Миниатюра')),
                ('is_main', models.BooleanField(default=False, help_text='Отметьте, если это основное изображение продукта', verbose_name='Основное изображение')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание изображения')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
            ],
            options={
                'verbose_name': 'Изображение продукта',
                'verbose_name_plural': 'Изображения продуктов',
                'ordering': ['-is_main', 'uploaded_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Неликвид', 'verbose_name_plural': 'Неликвиды'},
        ),
        migrations.AlterModelOptions(
            name='subdivision',
            options={'ordering': ['name'], 'verbose_name': 'Подразделение', 'verbose_name_plural': 'Подразделения'},
        ),
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('new', 'Новое'), ('used', 'Б/у'), ('defective', 'Неисправное'), ('for_parts', 'На запчасти')], default='used', max_length=20, verbose_name='Состояние'),
        ),
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(blank=True, help_text='Конкретное место хранения на складе/в цехе', max_length=200, verbose_name='Место хранения'),
        ),
        migrations.AddField(
            model_name='product',
            name='notes',
            field=models.TextField(blank=True, help_text='Дополнительные заметки', verbose_name='Примечания'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999)], verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('available', '✅ Доступен'), ('reserved', '⏳ Зарезервирован'), ('used', '✅ Использован'), ('written_off', '❌ Списано')], default='available', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата постановки на хранение'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default='шт.', help_text='шт., кг., м., упак.', max_length=20, verbose_name='Единица измерения'),
        ),
        migrations.AddField(
            model_name='subdivision',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Ответственный за подразделение', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_subdivisions', to=settings.AUTH_USER_MODEL, verbose_name='Руководитель подразделения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='characteristics',
            field=models.JSONField(blank=True, default=dict, help_text='Дополнительные характеристики в формате ключ-значение', verbose_name='Характеристики'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(db_index=True, help_text='Уникальный код продукции (артикул, серийный номер)', max_length=100, verbose_name='Код продукции'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_products', to=settings.AUTH_USER_MODEL, verbose_name='Кем создан'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Подробное описание продукции', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Полное наименование продукции', max_length=200, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subdivision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.subdivision', verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='subdivision',
            name='code',
            field=models.CharField(help_text='Уникальный код подразделения (например, ЦЕХ-01)', max_length=50, unique=True, verbose_name='Код подразделения'),
        ),
        migrations.AlterField(
            model_name='subdivision',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='subdivision',
            name='description',
            field=models.TextField(blank=True, help_text='Дополнительная информация о подразделении', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='subdivision',
            name='name',
            field=models.CharField(help_text='Полное название подразделения', max_length=200, verbose_name='Название подразделения'),
        ),
        migrations.AlterField(
            model_name='subdivision',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['code'], name='catalog_pro_code_31976d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['subdivision'], name='catalog_pro_subdivi_bd94a5_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status'], name='catalog_pro_status_521020_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['condition'], name='catalog_pro_conditi_b60ced_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='catalog_pro_created_92b554_idx'),
        ),
        migrations.AddIndex(
            model_name='subdivision',
            index=models.Index(fields=['code'], name='catalog_sub_code_619ef0_idx'),
        ),
        migrations.AddIndex(
            model_name='subdivision',
            index=models.Index(fields=['name'], name='catalog_sub_name_051213_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('code', 'subdivision'), name='unique_product_code_per_subdivision'),
        ),
        migrations.AddField(
            model_name='changelog',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кем изменено'),
        ),
        migrations.AddField(
            model_name='changelog',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='catalog.product', verbose_name='Продукт'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='Продукт'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='uploaded_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кем загружено'),
        ),
    ]
