# Generated by Django 6.0.1 on 2026-01-20 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_changelog_productimage_alter_product_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubdivisionAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('viewer', '👁️ Только просмотр'), ('editor', '✏️ Редактирование своих записей'), ('admin', '⚙️ Администратор подразделения'), ('manager', '👑 Руководитель подразделения')], default='viewer', max_length=20, verbose_name='Уровень доступа')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата предоставления')),
                ('valid_until', models.DateTimeField(blank=True, help_text='Если пусто - бессрочно', null=True, verbose_name='Действует до')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_accesses', to=settings.AUTH_USER_MODEL, verbose_name='Кем предоставлен доступ')),
                ('subdivision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='catalog.subdivision', verbose_name='Подразделение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdivision_accesses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Доступ пользователя к подразделению',
                'verbose_name_plural': 'Доступы пользователей к подразделениям',
                'indexes': [models.Index(fields=['user', 'subdivision'], name='catalog_use_user_id_8d3935_idx'), models.Index(fields=['access_level'], name='catalog_use_access__814ddb_idx')],
                'unique_together': {('user', 'subdivision')},
            },
        ),
    ]
