# Generated by Django 6.0.1 on 2026-01-20 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_usersubdivisionaccess'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Должность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.AlterUniqueTogether(
            name='usersubdivisionaccess',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='usersubdivisionaccess',
            name='catalog_use_user_id_8d3935_idx',
        ),
        migrations.RemoveIndex(
            model_name='usersubdivisionaccess',
            name='catalog_use_access__814ddb_idx',
        ),
        migrations.AddField(
            model_name='profile',
            name='subdivision',
            field=models.ForeignKey(blank=True, help_text='Подразделение, к которому привязан пользователь', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='catalog.subdivision', verbose_name='Подразделение'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.DeleteModel(
            name='UserSubdivisionAccess',
        ),
    ]
